### ISSUE TITLE
Product, Orders, Order classes conform to NSCoding, but don't adopt it. 

### ISSUE THREAD

**Issue by AndrewJByrne** [codeschool/AppEvolutionWithSwiftDemo#3]
Swift newbie here. I followed the [Soup to Bits](https://www.codeschool.com/screencasts/soup-to-bits-app-evolution-with-swift) video today and coded up the enhancements from the course. I then looked at this repo to compare what I did. 

In the video (for example around the 49:44 mark) you seem to implement the NSCoding protocol in the Orders class and then you also defined the class as adopting NSCoding. You repeat this for Order and Product - each one implementing init and the various encoders etc. 

When I looked at this repo, I saw each class omitted NSCoding from the class definition, yet implement exactly it as per the video.  For example, see the [Orders.swift class](https://github.com/codeschool/AppEvolutionWithSwiftDemo/blob/master/GoodAsOldPhones-SoupToBits/GoodAsOldPhones/Orders.swift) in this repo. `NSCoding` is missing after `NSObject` and that's different than what's shown in the video. 

Was NSCoding left out from the class definition on purpose? If so, why? Does adopting a protocol explicitly versus just implementing the methods that make up that protocol have any impact or advantages?

Again, rookie here, so making sure I haven't missed something.  

thanks,
Andrew

**Comment by jonfriskics** [comment]
Great question.  Until you mentioned it I didn't even realize we skipped adopting it.

I just played around in a couple of different apps and I'm confused by the behavior I'm seeing.  I'm able to use those NSCoding methods in my implementation even when I'm not adopting the protocol anywhere in my app (created a sample app).  I'll look into this a bit more this week, but I'm thinking it might be a bug because it's not normal that you can implement methods from a protocol without adopting it.

**Comment by AndrewJByrne** [comment]
Thanks for the speedy response, Jon! I'm looking forward to hearing the outcome. I'm not blocked by this in terms of coding as I have adopted NSCoding in my classes, but curious to hear the final outcome.

**Comment by jonfriskics** [comment]
Haven't forgotten about this - was away at an offsite all last week but I'm still looking into it.

**Comment by AndrewJByrne** [comment]
No worries Jon. Thanks for the update!

**Comment by jonfriskics** [comment]
Dug around some more and asked on the official Apple forums, and it turns out that since the NSKeyedArchiver methods are the ones that are actually calling the init?(coder) and encodeWithCoder() methods that you don't actually need to adopt NSCoding - although it's probably a good idea so other people reading your code can see that's what your class is doing.

If you do adopt NSCoding and don't implement those methods then Xcode will yell at you, but if you just add the methods and don't adopt the protocol it looks like the NSKeyedArchiver `archiveRootObject` method is just calling a function with the name `encodeWithCoder` under the hood.  That's why it worked without adopting that protocol in the app we made in the video - and in fact it would work without adopting those at all.

Glad you pointed this out because I learned something here too!

**Comment by AndrewJByrne** [comment]
Thanks for digging around. It sounds like I'm fine either way.  What I also noticed is that neither the `encodeWithCoder` method nor the `init` overrides are needed/invoked in the `Orders` class at all and my archiving still works fine. I set breakpoints and they are never called. Only the `Order` class needs those methods in this project. So, I trimmed my Orders class as follows:

``` swift
import UIKit

class Orders: NSObject {
    var orders: [Order]?

    class func archiveFilePath() -> String {
        let documentsDictionary = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]

        let path = documentsDictionary.URLByAppendingPathComponent("cart.archive").path!

        return path
    }

    class func readOrdersFromArchive() -> [Order] {
        return NSKeyedUnarchiver.unarchiveObjectWithFile(archiveFilePath()) as? [Order] ?? []
    }

    class func saveOrdersToArchive(orders: [Order]) -> Bool {
        return NSKeyedArchiver.archiveRootObject(orders, toFile: archiveFilePath())
    }

}
```

Sorry for dragging on this thread, but do you see this as a worthy update?

**Comment by jonfriskics** [comment]
Hey Andrew,

Thinking about this some more - you're right, you shouldn't need the init/encode methods on the Orders class because that's just serializing an array (of Order objects) which is something that doesn't need explicit instructions - but I believe you'd still need to implement those on the Product and Order classes as instructions for how to serialize that data.

**Comment by AndrewJByrne** [comment]
Excellent! Thanks Jon
